# Vespa 管理ノード StatefulSet
# Admin node StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vespa.fullname" . }}-admin
  labels:
    {{- include "vespa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: {{ include "vespa.fullname" . }}-admin
      name: {{ include "vespa.internalService" . }}
  serviceName: {{ include "vespa.internalService" . }}
  template:
    metadata:
      labels:
        app: {{ include "vespa.fullname" . }}-admin
        name: {{ include "vespa.internalService" . }}
    spec:
      initContainers:
        - name: chown-var
          securityContext:
            runAsUser: 0
          image: busybox
          command: ["sh", "-c", "chown -R 1000 /opt/vespa/var"]
          volumeMounts:
            - name: vespa-var
              mountPath: /opt/vespa/var
      containers:
        - name: vespa-admin
          image: {{ include "vespa.image" . }}
          args: ["services"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
          envFrom:
            - configMapRef:
                name: {{ include "vespa.fullname" . }}-config
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          volumeMounts:
            - name: vespa-var
              mountPath: /opt/vespa/var
  volumeClaimTemplates:
    - metadata:
        name: vespa-var
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storageClass | quote }}
        resources:
          requests:
            storage: 2Gi
